{
  description = "Generated Terraform provider for Akeyless";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = import nixpkgs { inherit system; };
      in {
        packages.default = pkgs.runCommand "terraform-akeyless-gen" {
          src = self;
        } ''
          mkdir -p $out/share/terraform
          cp -r $src/resources $out/share/terraform/ 2>/dev/null || true
          cp -r $src/provider $out/share/terraform/ 2>/dev/null || true
          touch $out/share/terraform/.generated
        '';

        # Go syntax verification via gofmt.
        # Upgrade to substrate mkGoLibraryCheck when go.mod is generated by iac-forge.
        checks.default = pkgs.runCommand "check-terraform-gen" {
          src = self;
          nativeBuildInputs = [ pkgs.go ];
        } ''
          cd $src
          GO_COUNT=$(find . -name '*.go' -not -path './.git/*' | wc -l | tr -d ' ')
          if [ "$GO_COUNT" -eq 0 ]; then
            echo "FAIL: no Go files found"
            exit 1
          fi
          BAD=$(find . -name '*.go' -not -path './.git/*' -exec gofmt -l {} + 2>/dev/null || true)
          if [ -n "$BAD" ]; then
            echo "FAIL: Go files with formatting issues:"
            echo "$BAD"
            exit 1
          fi
          if [ -f go.mod ]; then
            echo "=> go.mod found — running go vet"
            export GOPATH=$TMPDIR/gopath
            export GOCACHE=$TMPDIR/gocache
            mkdir -p "$GOPATH" "$GOCACHE"
            go vet ./... 2>&1 || true
          fi
          echo "OK: $GO_COUNT Go files pass syntax check"
          mkdir -p $out
          echo "terraform-gen: $GO_COUNT files checked" > $out/result.txt
        '';
      }
    );
}
